Restore code in memoverride
noexcept was commented out and causing issues.

" Error C2382 '_msize_base': redefinition"

This error occurred in roughly 15 other files that referenced this line.

After restoring this line, I was able to successfully compile once more.

If this was removed for a reason, the code needs refactored to compensate.